server:
  port: 8081

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1434;DatabaseName=NLP;trustServerCertificate=true
    username: sa
    password: szy19991006
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    druid:
      #?????
      initialSize: 5
      #???
      minIdle: 5
      #???
      maxActive: 20
      #??????????????????????????ms
      maxWait: 60000
      #?????????????????????????
      timeBetweenEvictionRunsMillis: 60000
      #????????????????
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true

      filters: stat,wall,log4j2

      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true

      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

      web-stat-filter:

        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      #??StatViewServlet
      stat-view-servlet:
        url-pattern: "/druid/*"
        #????ip
        allow: 127.0.0.1
        login-username: admin
        login-password: 123456
        #????ip
        deny: 192.168.1.102
        #??????
        reset-enable: true
        #??
        enabled: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    active: dev

# Mybatis??
mybatis:
  # ??XML???????????????
  type-aliases-package: com.example.pojo
  # ??MyBatis?xml??????
  mapper-locations: classpath*:com/**/mapper/*.xml



# ??sql
logging:
  level:
    ssm.app.mapper : debug

