server:
    port: 8081

spring:
    datasource:
        url: jdbc:sqlserver://localhost:1434;DatabaseName=NLP;trustServerCertificate=true
        username: sa
        password: szy19991006
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher
    profiles:
        active: dev



# ??sql
logging:
    level:
        ssm.app.mapper : debug